name: PBL3 CU

on:
  push: 
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pbl3-image:${{ github.sha }} .
      - name: Push image to docker hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pbl3-image:${{ github.sha }}

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to the server
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pbl3-image:${{ github.sha }}

          docker stop pbl3-container || true
          docker rm pbl3-container || true 

          docker run -d -p 80:3000 --name pbl3-container ${{ secrets.DOCKERHUB_USERNAME }}/pbl3-image:${{ github.sha }}
