name: PBL3 CU

on:
  push: 
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker build -t pbl3-image .
      - name: Push image to docker hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pbl3-image:${{ github.sha }}
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: log private key
        uses: echo ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to the server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pbl3-image:${{ github.sha }}

            docker stop pbl3-image
            docker rm pbl3-image

            docker run -d -p 80:3000 --name pbl3-container ${{ secrets.DOCKERHUB_USERNAME }}/pbl3-image:${{ github.sha }} 
          
